name: Deploy Converter to Container
on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Yandex Container Registry
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YANDEX_SECRET_KEY }}

      - name: Build and Push Docker Image
        run: |
          docker build -t cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/media-converter:latest .
          docker push cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/media-converter:latest

      - name: Deploy Serverless Container via YC CLI
        run: |
          # 1. Записываем ключ во временный файл для авторизации
          echo '${{ secrets.YANDEX_SECRET_KEY }}' > sa_key.json
          
          # 2. Устанавливаем и настраиваем YC CLI
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          export PATH=$PATH:/home/runner/yandex-cloud/bin
          
          yc config profile create sa-profile
          yc config set service-account-key sa_key.json
          yc config set folder-id ${{ secrets.YANDEX_FOLDER_ID }}

          # 3. Создаем или обновляем контейнер
          # Если контейнера нет, он создастся. Если есть — создаст новую ревизию.
          yc serverless container revision deploy \
            --container-name leshiy-media-converter \
            --image cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/media-converter:latest \
            --cores 1 \
            --memory 1GB \
            --concurrency 16 \
            --execution-timeout 60s \
            --service-account-id ${{ secrets.YANDEX_SERVICE_ID }} \
            --environment PORT=3000,DEBUG=true,APP_DOMAIN=https://d5dtt5rfr7nk66bbrec2.kf69zffa.apigw.yandexcloud.net/converter